-- Step 1: Check if there are existing workout details that reference exercises
-- This is a safety check to prevent data loss
SELECT COUNT(*) INTO @workout_count FROM workout_details;

-- Only proceed if there are no workout details
SET @can_proceed = IF(@workout_count = 0, 1, 0);

-- Display a warning message if we can't proceed
SELECT IF(@can_proceed = 0, 'WARNING: Cannot reset exercise library. There are workout details that reference exercises. Export and delete your training data first.', 'Proceeding with exercise library reset...') AS 'Status';

-- Only execute the reset if safe to do so
START TRANSACTION;

-- Step 2: If safe, delete all data from the exercise-related tables
DELETE FROM exercises WHERE @can_proceed = 1;
DELETE FROM equipment WHERE @can_proceed = 1;
DELETE FROM muscle_groups WHERE @can_proceed = 1;

-- Step 3: Reset auto-increment counters
ALTER TABLE exercises AUTO_INCREMENT = 1;
ALTER TABLE equipment AUTO_INCREMENT = 1;
ALTER TABLE muscle_groups AUTO_INCREMENT = 1;

-- Step 4: Create temporary table to hold the imported data
CREATE TEMPORARY TABLE IF NOT EXISTS temp_exercise_import (
    muscle_group VARCHAR(50),
    equipment VARCHAR(50),
    exercise_name VARCHAR(100),
    description TEXT
);

-- Step 5: Insert exercise data directly into the temporary table
-- This replaces LOAD DATA INFILE with direct INSERT statements

INSERT INTO temp_exercise_import (muscle_group, equipment, exercise_name, description) VALUES
('Abdominals', 'Barbell', 'Barbell Landmine Side Bend', 'A side bend exercise using a barbell landmine setup to target the obliques while providing resistance throughout the movement.'),
('Abdominals', 'Barbell', 'Barbell Roll Outs', 'Starting in a kneeling position, rolling a barbell forward to extend the body while maintaining core tension.'),
('Abdominals', 'Barbell', 'Barbell Situp', 'A situp variation performed while holding a barbell across the chest for added resistance.'),
('Abdominals', 'Barbell', 'Landmine Hollow Hold', 'Maintaining a hollow body position while holding the end of a landmine bar to increase core stability.'),
('Abdominals', 'Barbell', 'Landmine Kneeling Twist', 'A rotational core exercise performed in a kneeling position using a landmine for resistance.'),
('Abdominals', 'Barbell', 'Landmine Oblique Twist', 'A standing rotational exercise using a landmine to target the obliques through controlled twisting movements.'),
('Abdominals', 'Barbell', 'Landmine Russian Twist', 'A seated twisting exercise using a landmine to target the obliques and deep core muscles.'),
('Abdominals', 'Barbell', 'Landmine Sit Up', 'A situp variation incorporating a landmine bar for added resistance and rotational component.'),
('Abdominals', 'Barbell', 'Landmine Stationary Twist', 'A standing core rotation exercise using fixed foot positioning and landmine for resistance.'),
('Abdominals', 'Bodyweight', 'Alternating Bent Leg Raise', 'Lying on back and raising one bent knee at a time toward the chest to target lower abs.'),
('Abdominals', 'Bodyweight', 'Alternating Heel Touch', 'A crunch variation where you alternately reach down to touch each heel to target obliques.'),
('Abdominals', 'Bodyweight', 'Bicycle Crunch', 'A dynamic abdominal exercise involving simultaneous elbow-to-knee touches in a cycling motion.'),
('Abdominals', 'Bodyweight', 'Bird Dog', 'A core stability exercise performed on hands and knees, extending opposite arm and leg simultaneously.'),
('Abdominals', 'Bodyweight', 'Bodyweight Hanging Knee Tuck', 'Hanging from a bar and bringing knees toward chest to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Bodyweight Hanging L Sit', 'Hanging from a bar with legs extended straight out in front at 90 degrees to the body.'),
('Abdominals', 'Bodyweight', 'Bodyweight Knee Plank Up Down', 'Transitioning between forearm plank and hand plank positions while maintaining knees on ground.'),
('Abdominals', 'Bodyweight', 'Bodyweight Plank Up Down', 'Moving between forearm and hand plank positions while maintaining core tension.'),
('Abdominals', 'Bodyweight', 'Bodyweight Russian Twist', 'A seated rotational exercise targeting obliques by twisting side to side with elevated feet.'),
('Abdominals', 'Bodyweight', 'Bodyweight Situp', 'A basic abdominal exercise lying on back and rising to a seated position.'),
('Abdominals', 'Bodyweight', 'Burpee', 'A full-body exercise combining squat, pushup, and jump to elevate heart rate and target multiple muscle groups.'),
('Abdominals', 'Bodyweight', 'Crunches', 'A basic abdominal exercise lifting shoulders off the ground while engaging the core.'),
('Abdominals', 'Bodyweight', 'Dead Bug', 'A core stability exercise performed on back with alternating arm and leg movements.'),
('Abdominals', 'Bodyweight', 'Eccentric Dragonflag', 'A challenging core exercise where you lower your extended body in a controlled manner from a vertical position.'),
('Abdominals', 'Bodyweight', 'Elbow Plank Mountain Climber', 'Performing alternating knee drives toward chest while maintaining an elbow plank position.'),
('Abdominals', 'Bodyweight', 'Elbow Side Plank', 'A lateral core exercise supporting body weight on one elbow and side of feet.'),
('Abdominals', 'Bodyweight', 'Forearm Plank', 'An isometric core exercise holding a straight-body position supported by forearms and toes.'),
('Abdominals', 'Bodyweight', 'Frog Crunch', 'A crunch variation with knees wide and feet together to increase range of motion.'),
('Abdominals', 'Bodyweight', 'Frog Sit Up', 'A situp variation with knees wide and feet together to increase hip mobility and core engagement.'),
('Abdominals', 'Bodyweight', 'Hand Plank', 'An isometric core exercise in a pushup-top position with body in straight line.'),
('Abdominals', 'Bodyweight', 'Hand Side Plank', 'A lateral core exercise supporting body weight on one hand and side of feet.'),
('Abdominals', 'Bodyweight', 'Hand Side Plank Reach Through', 'A side plank variation with a rotational component reaching the top arm underneath the body.'),
('Abdominals', 'Bodyweight', 'Hanging Knee Raises', 'Hanging from a bar and lifting knees toward chest to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Hollow Hold', 'An isometric core exercise lying on back with arms and legs extended and lower back pressed to floor.'),
('Abdominals', 'Bodyweight', 'Jumping Mountain Climber', 'An explosive variation of mountain climbers adding a jumping element for increased intensity.'),
('Abdominals', 'Bodyweight', 'Laying Alternating Leg Raise', 'Lying on back and raising one straight leg at a time to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Laying Bent Leg Raise', 'Lying on back and raising bent legs toward chest to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Laying Leg Raises', 'Lying on back and raising both straight legs to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Long Lever Forearm Plank', 'A more challenging forearm plank with arms extended further forward to increase leverage.'),
('Abdominals', 'Bodyweight', 'Long Lever Plank', 'A more challenging hand plank with arms extended further forward to increase leverage.'),
('Abdominals', 'Bodyweight', 'Mountain Climber', 'A dynamic core exercise in plank position alternately driving knees toward chest.'),
('Abdominals', 'Bodyweight', 'Oblique Crunch', 'A crunch variation targeting the obliques by twisting upper body during the movement.'),
('Abdominals', 'Bodyweight', 'Oblique Jackknife', 'A side-lying exercise bringing elbow and knee together to target obliques.'),
('Abdominals', 'Bodyweight', 'Plank 2 Saw', 'A plank variation with forward-backward shifting to increase core engagement.'),
('Abdominals', 'Bodyweight', 'Reach And Catch', 'A hollow hold variation with arm movements to challenge core stability.'),
('Abdominals', 'Bodyweight', 'Reverse Crunch', 'Lying on back and lifting hips off ground to target lower abdominals.'),
('Abdominals', 'Bodyweight', 'Reverse Crunch Kick Up', 'A reverse crunch with an extended leg kick at the top of the movement.'),
('Abdominals', 'Bodyweight', 'Ring Standing Roll Out', 'A progression of ab rollouts performed with gymnastic rings from a standing position.'),
('Abdominals', 'Bodyweight', 'Scissor Kick', 'A core exercise lying on back and alternating straight leg raises in a scissoring motion.'),
('Abdominals', 'Bodyweight', 'Side Plank Reach Through', 'Rotating from side plank to reach arm underneath the body to target obliques.'),
('Abdominals', 'Bodyweight', 'Side Plank Up Down', 'Transitioning between forearm and hand side plank positions while maintaining alignment.'),
('Abdominals', 'Bodyweight', 'Sideways Scissor Kick', 'A variation of scissor kicks with a lateral component to target obliques.'),
('Abdominals', 'Bodyweight', 'Slalom Mountain Climber', 'A mountain climber variation with diagonal knee drives mimicking skiing motions.'),
('Abdominals', 'Bodyweight', 'Slow Tempo Mountain Climber', 'Mountain climbers performed at a deliberate pace to increase time under tension.'),
('Abdominals', 'Bodyweight', 'Switch Jump Mountain Climber', 'An explosive mountain climber variation with a jumping switch of foot positions.'),
('Abdominals', 'Bodyweight', 'Windshield Wiper', 'Lying on back with legs extended upward and rotating them side to side to target obliques.'),
('Abdominals', 'Cables', 'Cable Half Kneeling High To Low Wood Chopper', 'A rotational exercise in half-kneeling position pulling cable diagonally downward.'),
('Abdominals', 'Cables', 'Cable Half Kneeling Low To High Wood Chopper', 'A rotational exercise in half-kneeling position pulling cable diagonally upward.'),
('Abdominals', 'Cables', 'Cable Half Kneeling Wood Chopper', 'A rotational core exercise in half-kneeling position using cable resistance.'),
('Abdominals', 'Cables', 'Cable Oblique Pushdown', 'A standing cable exercise pushing downward and across the body to target obliques.'),
('Abdominals', 'Cables', 'Cable Pallof Press', 'An anti-rotation core exercise extending arms horizontally while resisting cable pull.'),
('Abdominals', 'Cables', 'Cable Pallof Press Rotation', 'A pallof press variation adding a rotational component to increase difficulty.'),
('Abdominals', 'Cables', 'Cable Rope Kneeling Crunch', 'A kneeling abdominal exercise pulling a rope attachment toward knees.'),
('Abdominals', 'Cables', 'Cable Rope Kneeling Oblique Crunch', 'A kneeling cable crunch with rotation to target the obliques.'),
('Abdominals', 'Cables', 'Cable Row Bar Kneeling Crunch', 'A kneeling abdominal exercise pulling a straight bar attachment toward knees.'),
('Abdominals', 'Cables', 'Cable Side Bend', 'A standing lateral flexion exercise using cable resistance to target obliques.'),
('Abdominals', 'Cables', 'Cable Standing Crunch', 'A standing abdominal exercise pulling cable downward to simulate crunch movement.'),
('Abdominals', 'Cables', 'Cable Wood Chopper', 'A diagonal cable exercise mimicking a chopping motion to target rotational core strength.'),
('Abdominals', 'Dumbbells', 'Dumbbell Crunch', 'A crunch holding a dumbbell at chest or overhead for added resistance.'),
('Abdominals', 'Dumbbells', 'Dumbbell Elbow Side Plank', 'A side plank on elbow while holding a dumbbell with the top arm.'),
('Abdominals', 'Dumbbells', 'Dumbbell Half Kneeling Wood Chopper', 'A rotational exercise in half-kneeling position using dumbbell resistance.'),
('Abdominals', 'Dumbbells', 'Dumbbell Hand Side Plank', 'A side plank on hand while holding a dumbbell with the top arm.'),
('Abdominals', 'Dumbbells', 'Dumbbell Hollow Hold', 'A hollow hold with dumbbells extended overhead for increased challenge.'),
('Abdominals', 'Dumbbells', 'Dumbbell Kneeling Wood Chopper', 'A rotational core exercise in kneeling position using dumbbell resistance.'),
('Abdominals', 'Dumbbells', 'Dumbbell Long Lever Russian Twist', 'A Russian twist with arms extended further to increase leverage and difficulty.'),
('Abdominals', 'Dumbbells', 'Dumbbell Overhead Side Bend', 'A standing lateral flexion holding a dumbbell overhead to target obliques.'),
('Abdominals', 'Dumbbells', 'Dumbbell Plank Pullthrough', 'In plank position, pulling a dumbbell from one side of body to the other while maintaining stability.'),
('Abdominals', 'Dumbbells', 'Dumbbell Renegade Row', 'A plank position row alternating arms while maintaining core stability.'),
('Abdominals', 'Dumbbells', 'Dumbbell Russian Twist', 'A seated rotational exercise using a dumbbell to target obliques.'),
('Abdominals', 'Dumbbells', 'Dumbbell Side Bend', 'A standing lateral flexion exercise using dumbbell resistance to target obliques.'),
('Abdominals', 'Dumbbells', 'Dumbbell Side Plank Up Down', 'Transitioning between forearm and hand side plank while holding a dumbbell.'),
('Abdominals', 'Dumbbells', 'Dumbbell Situp', 'A situp performed while holding a dumbbell at chest for added resistance.'),
('Abdominals', 'Dumbbells', 'Dumbbell Suitcase Crunch', 'A crunch variation holding dumbbells at shoulders through the movement.'),
('Abdominals', 'Dumbbells', 'Dumbbell Wood Chopper', 'A diagonal dumbbell exercise mimicking a chopping motion to target rotational core strength.'),
('Abdominals', 'Dumbbells', 'Plank Iytw', 'A plank position exercise with arm movements in I, Y, T, and W patterns for shoulder and core development.'),
('Abdominals', 'Dumbbells', 'Pushup To Renegade Row', 'A combination exercise alternating between pushups and renegade rows.'),
('Abdominals', 'Machine', 'Machine Roll Outs', 'An ab rollout exercise performed using a specialized machine for controlled movement.'),
('Abdominals', 'Machine', 'Rower Knee Tuck', 'Using a rowing machine to perform knee tucks toward chest to target abdominals.'),
('Abdominals', 'Machine', 'Rower Pike', 'Using a rowing machine to perform a pike movement lifting hips upward to target abdominals.'),
('Abdominals', 'Smith Machine', 'Smith Machine Hanging Knee Tuck', 'Hanging from a Smith machine bar and bringing knees toward chest.'),
('Abdominals', 'Smith Machine', 'Smith Machine Oblique Crunch', 'A crunch with rotational component using Smith machine for support or resistance.'),
('Abdominals', 'Smith Machine', 'Smith Machine Reverse Crunch Hip Raise', 'A reverse crunch lifting hips off ground using Smith machine for support or resistance.'),
('Abdominals', 'Smith Machine', 'Smith Machine Side Bend', 'A lateral flexion exercise using a Smith machine bar for resistance.'),
('Abdominals', 'Smith Machine', 'Smith Machine Side Plank Up Down', 'Transitioning between forearm and hand side plank using Smith machine for support.'),
('Abdominals', 'Smith Machine', 'Smith Machine Situp', 'A situp exercise using Smith machine for support or added resistance.'),
('Biceps', 'Barbell', 'Barbell Curl', 'A standing exercise curling a barbell from extended arms position to shoulders.'),
('Biceps', 'Barbell', 'Barbell Drag Curl', 'A curl variation keeping elbows back and bar close to body throughout movement.'),
('Biceps', 'Barbell', 'Barbell Reverse Curl', 'A curl using pronated (overhand) grip to target brachialis and forearms.'),
('Biceps', 'Barbell', 'Ez Bar Preacher Curl', 'A supported curl using angled bar on preacher bench to isolate biceps.'),
('Biceps', 'Barbell', 'Ez Bar Reverse Preacher Curl', 'A preacher curl using pronated grip to target brachialis and forearms.'),
('Biceps', 'Barbell', 'Landmine Bicep Curl', 'A curl exercise using the end of a landmine apparatus for variable resistance.'),
('Biceps', 'Barbell', 'Landmine Concentration Curl', 'A single-arm curl using landmine apparatus for isolated bicep development.'),
('Biceps', 'Bodyweight', 'Bodyweight Assisted Chin Up', 'A chin-up with partial body weight supported to build pulling strength.'),
('Biceps', 'Bodyweight', 'Bodyweight Assisted Gironda Chin Up', 'A sternum pull-up variation with support to build upper back and biceps.'),
('Biceps', 'Bodyweight', 'Bodyweight Assisted Mixed Grip Pullup', 'A pull-up using both overhand and underhand grips with assistance.'),
('Biceps', 'Bodyweight', 'Bodyweight Assisted Pull Up', 'A pull-up with partial body weight supported to build pulling strength.'),
('Biceps', 'Bodyweight', 'Bodyweight Close Grip Inverted Curl', 'A supine row with hands close together to emphasize biceps.'),
('Biceps', 'Bodyweight', 'Bodyweight Concentration Curl', 'An isometric bicep exercise using one arm to create resistance for the other.'),
('Biceps', 'Bodyweight', 'Bodyweight Inverted Curl', 'A supine row using underhand grip to target biceps.'),
('Biceps', 'Bodyweight', 'Bodyweight Underhand Inverted Row', 'A horizontal pulling exercise using underhand grip to target biceps.'),
('Biceps', 'Bodyweight', 'Chin Ups', 'Pulling body upward on bar using underhand grip to target biceps and back.'),
('Biceps', 'Bodyweight', 'Ring Curl', 'A bicep curl performed using gymnastic rings for instability challenge.'),
('Biceps', 'Bodyweight', 'Ring Row', 'A horizontal pulling exercise using gymnastic rings for back and biceps.'),
('Biceps', 'Cables', 'Cable Bar Curl', 'A standing curl using straight bar attachment on cable machine.'),
('Biceps', 'Cables', 'Cable Bilateral Bayesian Curl', 'A curl variation maintaining constant tension via cable positioning.'),
('Biceps', 'Cables', 'Cable Hammer Bayesian Curl', 'A neutral-grip curl variation maintaining constant tension via cable positioning.'),
('Biceps', 'Cables', 'Cable Reverse Bayesian Curl', 'A pronated-grip curl variation maintaining constant tension via cable positioning.'),
('Biceps', 'Cables', 'Cable Rope Hammer Curl', 'A curl using rope attachment with neutral grip to target biceps and brachialis.'),
('Biceps', 'Cables', 'Cable Seated Bayesian Curl', 'A seated curl variation maintaining constant tension via cable positioning.'),
('Biceps', 'Cables', 'Cable Seated Bayesian Hammer Curl', 'A seated neutral-grip curl variation maintaining constant tension.'),
('Biceps', 'Cables', 'Cable Seated Bayesian Reverse Curl', 'A seated pronated-grip curl variation maintaining constant tension.'),
('Biceps', 'Cables', 'Cable Single Arm Bayesian Curl', 'A unilateral curl variation maintaining constant tension via cable positioning.'),
('Biceps', 'Cables', 'Cable Single Arm Hammer Curl', 'A unilateral curl using neutral grip on cable machine.'),
('Biceps', 'Cables', 'Cable Single Arm Reverse Curl', 'A unilateral curl using pronated grip on cable machine.'),
('Biceps', 'Cables', 'Cable Twisting Curl', 'A curl with forearm rotation from pronated to supinated grip during movement.'),
('Biceps', 'Dumbbells', 'Dumbbell Concentration Curl', 'A seated single-arm curl with elbow braced against inner thigh for isolation.'),
('Biceps', 'Dumbbells', 'Dumbbell Curl', 'A standing exercise curling dumbbells from extended arms position to shoulders.'),
('Biceps', 'Dumbbells', 'Dumbbell Hammer Curl', 'A curl using neutral grip (thumbs up) to target biceps and brachialis.'),
('Biceps', 'Dumbbells', 'Dumbbell Incline Hammer Curl', 'A hammer curl performed on an inclined bench for increased stretch.'),
('Biceps', 'Dumbbells', 'Dumbbell Incline Reverse Curl', 'A pronated-grip curl performed on an inclined bench for increased stretch.'),
('Biceps', 'Dumbbells', 'Dumbbell Incline Zottman Curl', 'A curl on incline bench with rotation from supinated to pronated grip at top.'),
('Biceps', 'Dumbbells', 'Dumbbell Preacher Curl', 'A supported curl using dumbbells on preacher bench to isolate biceps.'),
('Biceps', 'Dumbbells', 'Dumbbell Reverse Curl', 'A curl using pronated (overhand) grip to target brachialis and forearms.'),
('Biceps', 'Dumbbells', 'Dumbbell Single Arm Preacher Curl', 'A unilateral supported curl using preacher bench for isolation.'),
('Biceps', 'Dumbbells', 'Dumbbell Single Arm Spider Curl', 'A unilateral curl performed lying chest-down on incline bench.'),
('Biceps', 'Dumbbells', 'Dumbbell Spider Curl', 'A curl performed lying chest-down on incline bench for increased isolation.'),
('Biceps', 'Dumbbells', 'Dumbbell Twisting Curl', 'A curl with forearm rotation from pronated to supinated grip during movement.'),
('Biceps', 'Machine', 'Machine Assisted Chin Up', 'A chin-up with partial machine support to build pulling strength.'),
('Biceps', 'Machine', 'Machine Assisted Narrow Pull Up', 'A close-grip pull-up with machine assistance to target inner back and biceps.'),
('Biceps', 'Machine', 'Machine Assisted Neutral Chin Up', 'A neutral-grip pull-up with machine assistance.'),
('Biceps', 'Machine', 'Machine Assisted Pull Up', 'A pull-up with partial machine support to build pulling strength.'),
('Biceps', 'Smith Machine', 'Smith Machine Drag Curl', 'A curl variation keeping elbows back and bar close to body using Smith machine.'),
('Upper_Back', 'Barbell', 'Barbell Bent Over Row', 'A compound pulling exercise bending at hips and pulling barbell to lower chest.'),
('Upper_Back', 'Barbell', 'Barbell Landmine Row', 'A row variation using landmine setup for easier body positioning.'),
('Upper_Back', 'Barbell', 'Barbell Long Landmine Row', 'A landmine row with wider stance for greater range of motion.'),
('Upper_Back', 'Barbell', 'Barbell Meadows Row', 'A unilateral row variation targeting upper back with specialized positioning.'),
('Upper_Back', 'Barbell', 'Barbell Pronated Pendlay Row', 'An explosive row from floor using overhand grip and horizontal torso.'),
('Upper_Back', 'Barbell', 'Barbell Pronated Row', 'A bent-over row using overhand grip to target upper back.'),
('Upper_Back', 'Barbell', 'Barbell Supinated Pendlay Row', 'An explosive row from floor using underhand grip and horizontal torso.'),
('Upper_Back', 'Barbell', 'Barbell Supinated Row', 'A bent-over row using underhand grip to emphasize lower lats and biceps.'),
('Upper_Back', 'Barbell', 'Landmine T Bar Rows', 'A row using landmine setup with close grip to target mid-back.'),
('Upper_Back', 'Cables', 'Cable Archer Row', 'A unilateral row mimicking archery movement for rotational back development.'),
('Upper_Back', 'Cables', 'Cable Pull In', 'A cable exercise pulling toward center of body to target lats and core.'),
('Upper_Back', 'Cables', 'Cable Single Arm Neutral Grip Row', 'A unilateral row using neutral grip handle for balanced back development.'),
('Upper_Back', 'Cables', 'Cable Single Arm Underhand Grip Row', 'A unilateral row using underhand grip to emphasize lower lats.'),
('Upper_Back', 'Cables', 'Cable Supinating Row', 'A row with forearm rotation from pronated to supinated grip during movement.'),
('Upper_Back', 'Cables', 'Cable Single Arm Row Bar Standing Row', 'A unilateral row using straight bar attachment for back development.'),
('Upper_Back', 'Cables', 'Cable Row Bar Standing Row', 'A bilateral standing row using straight bar attachment.'),
('Upper_Back', 'Machine', 'Machine Seated Cable Row', 'A seated horizontal pulling exercise using cable resistance.'),
('Upper_Back', 'Machine', 'Machine Underhand Row', 'A seated row using underhand grip to emphasize lower lats and biceps.'),
('Upper_Back', 'Machine', 'Machine Neutral Row', 'A seated row using neutral grip to target mid-back and biceps.'),
('Upper_Back', 'Machine', 'Machine Pulldown', 'A vertical pulling exercise targeting latissimus dorsi muscles.'),
('Upper_Back', 'Machine', 'Narrow Pulldown', 'A lat pulldown using close grip to target inner back muscles.'),
('Upper_Back', 'Machine', 'Neutral Pulldown', 'A lat pulldown using neutral grip to target balanced back development.'),
('Upper_Back', 'Machine', 'Underhand Pulldown', 'A lat pulldown using underhand grip to emphasize lower lats and biceps.'),
('Upper_Back', 'Machine', 'Stretcher', 'A machine-assisted stretch for lats and shoulder mobility.'),
('Upper_Back', 'Cables', 'Cable Bent Over Bar Pullover', 'A bent-over variation of pullover using cable for consistent tension.'),
('Upper_Back', 'Cables', 'Cable Lat Prayer', 'A kneeling pulldown variation with hands in prayer position targeting lats.'),
('Upper_Back', 'Cables', 'Cable Rope Lat Prayer', 'A kneeling pulldown using rope attachment with hands in prayer position.'),
('Upper_Back', 'Cables', 'Cable Rope Pullover', 'A pullover exercise using rope attachment for greater range of motion.'),
('Upper_Back', 'Cables', 'Cable Straight Arm Pull In', 'A standing pullover exercise with straight arms for lat isolation.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Pullover', 'A supine exercise moving dumbbell in arc over face to target lats and serratus.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Shoulder Extension', 'A prone exercise moving arms from overhead to sides targeting posterior shoulder and lats.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Alternating Pendlay Row', 'A unilateral explosive row from floor alternating arms.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Knee Lawnmower Row', 'A unilateral row with knee supported on bench mimicking lawnmower pulling motion.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Kneeling Single Arm Row', 'A unilateral row in half-kneeling position for stability.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Laying Incline Row', 'A prone row on incline bench for increased range of motion.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Pendlay Row', 'An explosive row from floor using dumbbells and horizontal torso.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Single Arm Row', 'A unilateral bent-over row supporting body with opposite arm.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Single Arm Row Knee', 'A unilateral row supporting body with knee and opposite arm on bench.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Supinated Row', 'A row using underhand grip to emphasize lower lats and biceps.'),
('Upper_Back', 'Dumbbells', 'Lawnmower Row', 'A unilateral row mimicking lawnmower pulling motion for functional back strength.'),
('Upper_Back', 'Dumbbells', 'Dumbbell Rear Delt Row', 'A row with elbows flared to target posterior deltoids and upper back.'),
('Upper_Back', 'Smith Machine', 'Smith Machine Overhand Row', 'A bent-over row using Smith machine with pronated grip.'),
('Upper_Back', 'Smith Machine', 'Smith Machine Underhand Row', 'A bent-over row using Smith machine with supinated grip.'),
('Upper_Back', 'Smith Machine', 'Smith Machine Assisted Pullup', 'A pull-up with feet supported on Smith machine bar.'),
('Upper_Back', 'Smith Machine', 'Smith Machine Inverted Row', 'A horizontal pulling exercise using fixed Smith machine bar.'),
('Calves', 'Barbell', 'Barbell Calf Jump', 'An explosive calf exercise combining calf raise with jump while holding barbell.'),
('Calves', 'Barbell', 'Barbell Calf Raises', 'A standing exercise lifting heels with barbell across shoulders.'),
('Calves', 'Barbell', 'Barbell Seated Calf Raise', 'A seated exercise lifting heels with barbell across knees.'),
('Calves', 'Barbell', 'Barbell Toes Up Calf Raise', 'A calf raise with toes elevated to target soleus muscle.'),
('Calves', 'Barbell', 'Landmine Calf Raise', 'A calf raise using landmine apparatus for varied resistance pattern.'),
('Calves', 'Barbell', 'Standing Tibialis Raise', 'An exercise lifting toes up while keeping heels on ground to target anterior tibialis.'),
('Calves', 'Bodyweight', 'Bodyweight Donkey Calf Raise', 'A calf raise performed with torso parallel to ground to target gastrocnemius.'),
('Calves', 'Bodyweight', 'Calf Raises', 'A basic standing heel raise to develop calf muscles.'),
('Calves', 'Bodyweight', 'Seated Tibialis Raise', 'A seated exercise lifting toes up to target anterior tibialis.'),
('Calves', 'Bodyweight', 'Tip Toe Walking', 'Walking on toes to develop calf endurance and stability.'),
('Calves', 'Bodyweight', 'Walking Calf Raises', 'Performing calf raises while walking for functional calf development.'),
('Calves', 'Cables', 'Cable Bar Calve Raise', 'A calf raise using cable bar attachment for resistance.'),
('Calves', 'Cables', 'Cable Calve Raise', 'A calf raise using cable resistance for variable tension.'),
('Calves', 'Dumbbells', 'Dumbbell Calf Raise', 'A standing calf raise while holding dumbbells for added resistance.'),
('Calves', 'Dumbbells', 'Dumbbell Seated Calf Raise', 'A seated calf raise with dumbbells on knees for resistance.'),
('Calves', 'Dumbbells', 'Dumbbell Seated Tibialis Raise', 'A seated exercise lifting toes while holding dumbbell on foot.'),
('Calves', 'Dumbbells', 'Dumbbell Standing Tibialis Raise', 'A standing exercise lifting toes while holding dumbbell on foot.'),
('Calves', 'Machine', 'Machine Horizontal Leg Press Calf Jump', 'An explosive calf exercise using leg press machine with jumping component.'),
('Calves', 'Machine', 'Machine Horizontal Leg Press Calf Raise', 'A calf raise performed on horizontal leg press machine.'),
('Calves', 'Machine', 'Machine Seated Calf Raises', 'A seated calf exercise using specialized machine for consistent resistance.'),
('Calves', 'Machine', 'Machine Standing Calf Raises', 'A standing calf exercise using specialized machine for consistent resistance.'),
('Calves', 'Smith Machine', 'Smith Machine Calf Raise', 'A standing calf raise using Smith machine bar across shoulders.'),
('Calves', 'Smith Machine', 'Smith Machine Seated Calf Raise', 'A seated calf raise using Smith machine bar across knees.'),
('Chest', 'Barbell', 'Barbell Larsen Bench Press', 'A bench press with legs elevated and feet not touching ground to reduce leg drive.'),
('Chest', 'Barbell', 'Barbell Hooklying Bench Press', 'A bench press with feet on bench and knees bent to eliminate leg drive.'),
('Chest', 'Barbell', 'Barbell Bench Press', 'A horizontal pressing exercise lying on bench with barbell.'),
('Chest', 'Barbell', 'Barbell High Incline Bench Press', 'A pressing exercise on high incline bench to target upper chest and front deltoids.'),
('Chest', 'Barbell', 'Barbell Incline Bench Press', 'A pressing exercise on incline bench to target upper chest.'),
('Chest', 'Barbell', 'Barbell Close Grip Bench Press', 'A bench press with hands positioned narrower than shoulder width to target triceps.'),
('Chest', 'Barbell', 'Barbell Floor Press', 'A pressing exercise performed on floor to limit range of motion and emphasize triceps.'),
('Chest', 'Barbell', 'Barbell Spoto Press', 'A bench press with pause holding bar above chest to eliminate stretch reflex.'),
('Chest', 'Bodyweight', 'Push Up', 'A horizontal pressing exercise in prone position using bodyweight resistance.'),
('Chest', 'Bodyweight', 'Ring Standing Chest Fly', 'A chest fly performed standing with gymnastic rings for increased stabilization.'),
('Chest', 'Cables', 'Cable Bench Chest Fly', 'A horizontal fly movement using cable resistance while lying on flat bench.'),
('Chest', 'Cables', 'Cable Decline Bench Chest Fly', 'A fly movement on decline bench using cable resistance to target lower chest.'),
('Chest', 'Cables', 'Cable Incline Bench Press', 'A pressing movement on incline bench using cable resistance.'),
('Chest', 'Cables', 'Cable Incline Chest Fly', 'A fly movement on incline bench using cable resistance to target upper chest.'),
('Chest', 'Cables', 'Cable Pec Fly', 'A standing horizontal adduction movement using cable to target chest.'),
('Chest', 'Cables', 'Cable Single Arm Bench Chest Fly', 'A unilateral fly movement on bench using cable resistance.'),
('Chest', 'Cables', 'Cable Single Arm Decline Bench Chest Fly', 'A unilateral fly on decline bench using cable resistance.'),
('Chest', 'Cables', 'Cable Single Arm Incline Chest Fly', 'A unilateral fly on incline bench using cable resistance.'),
('Chest', 'Cables', 'Cable Bench Press', 'A horizontal pressing exercise using cable resistance while lying on bench.'),
('Chest', 'Cables', 'Cable Chest Press', 'A standing horizontal pressing movement using cable resistance.'),
('Chest', 'Cables', 'Cable Decline Bench Press', 'A pressing movement on decline bench using cable resistance to target lower chest.'),
('Chest', 'Cables', 'Cable Decline Single Arm Bench Press', 'A unilateral pressing movement on decline bench using cable resistance.'),
('Chest', 'Cables', 'Cable Single Arm Bench Press', 'A unilateral pressing movement on flat bench using cable resistance.'),
('Chest', 'Cables', 'Cable Single Arm Incline Bench Press', 'A unilateral pressing movement on incline bench using cable resistance.'),
('Chest', 'Dumbbells', 'Dumbbell Chest Fly', 'A horizontal adduction movement lying on flat bench with dumbbells.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Chest Fly', 'A fly movement on decline bench using dumbbells to target lower chest.'),
('Chest', 'Dumbbells', 'Dumbbell Incline Chest Fly', 'A fly movement on incline bench using dumbbells to target upper chest.'),
('Chest', 'Dumbbells', 'Dumbbell Internally Rotated Chest Fly', 'A fly with internal rotation to better target chest fibers.'),
('Chest', 'Dumbbells', 'Dumbbell Internally Rotated Incline Chest Fly', 'An incline fly with internal rotation to better target upper chest fibers.'),
('Chest', 'Dumbbells', 'Dumbbell Bench Press', 'A horizontal pressing exercise lying on bench with dumbbells.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Bench Press', 'A pressing exercise on decline bench with dumbbells to target lower chest.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Neutral Bench Press', 'A decline press using neutral grip (palms facing each other) to target inner chest.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Alternating Single Arm Press', 'A unilateral press on decline bench alternating arms for core engagement.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Guillotine Bench Press', 'A decline press bringing dumbbells to neck area for upper chest emphasis.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Single Arm Bench Press', 'A unilateral press on decline bench for balanced development.'),
('Chest', 'Dumbbells', 'Dumbbell Decline Squeeze Press', 'A decline press squeezing dumbbells together to increase chest activation.'),
('Chest', 'Dumbbells', 'Dumbbell Elevated Pushup', 'A pushup with hands elevated on dumbbells for increased range of motion.'),
('Chest', 'Dumbbells', 'Dumbbell Floor Press', 'A pressing exercise lying on floor with dumbbells to limit range of motion.'),
('Chest', 'Dumbbells', 'Dumbbell Guillotine Bench Press', 'A bench press bringing dumbbells to neck area for upper chest emphasis.'),
('Chest', 'Dumbbells', 'Dumbbell Guillotine Incline Bench Press', 'An incline press bringing dumbbells to neck area for upper chest emphasis.'),
('Chest', 'Dumbbells', 'Dumbbell High Incline Bench Press', 'A pressing exercise on high incline bench targeting upper chest and front deltoids.'),
('Chest', 'Dumbbells', 'Dumbbell Incline Bench Press', 'A pressing exercise on incline bench with dumbbells targeting upper chest.'),
('Chest', 'Dumbbells', 'Dumbbell Neutral Bench Press', 'A bench press using neutral grip (palms facing each other) to target inner chest.'),
('Chest', 'Dumbbells', 'Dumbbell Neutral Incline Bench Press', 'An incline press using neutral grip to target inner upper chest.'),
('Chest', 'Dumbbells', 'Dumbbell Incline Chest Flys', 'A fly movement on incline bench using dumbbells to target upper chest.'),
('Chest', 'Dumbbells', 'Dumbbell Squeeze Press', 'A bench press squeezing dumbbells together throughout movement to increase chest activation.'),
('Chest', 'Dumbbells', 'Dumbbell Alternating Single Arm Press', 'A bench press alternating arms for increased core engagement and unilateral development.'),
('Chest', 'Dumbbells', 'Dumbbell Single Arm Press', 'A unilateral bench press targeting chest while engaging core for stabilization.'),
('Chest', 'Machine', 'Machine Chest Press', 'A horizontal pressing exercise using machine for consistent resistance path.'),
('Chest', 'Machine', 'Machine Pec Fly', 'A horizontal adduction machine targeting chest with fixed movement pattern.'),
('Chest', 'Machine', 'Neutral Chest Press', 'A machine chest press using neutral grip handles to target inner chest.'),
('Chest', 'Smith Machine', 'Smith Machine Bench Press', 'A bench press using fixed Smith machine bar path for stability.'),
('Chest', 'Smith Machine', 'Smith Machine Incline Bench Press', 'An incline press using Smith machine bar for upper chest development.'),
('Chest', 'Smith Machine', 'Smith Machine Pushup', 'A pushup with hands on Smith machine bar for elevated hand position.'),
('Forearms', 'Barbell', 'Barbell Behind The Back Wrist Curl', 'A wrist curl performed with barbell behind back to isolate forearm flexors.'),
('Forearms', 'Barbell', 'Barbell Wrist Curl', 'A forearm exercise curling weight upward using wrist flexion.'),
('Forearms', 'Barbell', 'Barbell Wrist Extension', 'A forearm exercise extending weight upward using wrist extension.'),
('Forearms', 'Cables', 'Cable Bar Reverse Grip Curl', 'A curl using pronated grip on cable machine to target forearms.'),
('Forearms', 'Cables', 'Cable Wrist Curl', 'A wrist flexion exercise using cable resistance for consistent tension.'),
('Forearms', 'Cables', 'Cable Wrist Extension', 'A wrist extension exercise using cable resistance for consistent tension.'),
('Forearms', 'Dumbbells', 'Dumbbell Bench Wrist Curl', 'A wrist curl with forearms supported on bench for isolation.'),
('Forearms', 'Dumbbells', 'Dumbbell Bench Wrist Extension', 'A wrist extension with forearms supported on bench for isolation.'),
('Forearms', 'Dumbbells', 'Dumbbell Wrist Curl', 'A seated or standing wrist flexion exercise using dumbbells.'),
('Forearms', 'Dumbbells', 'Dumbbell Wrist Extension', 'A seated or standing wrist extension exercise using dumbbells.'),
('Forearms', 'Dumbbells', 'Wrist Flexor Curl Dumbbell Kneeling', 'A wrist curl performed in kneeling position for stability.'),
('Forearms', 'Dumbbells', 'Wrist Supinations Pronations', 'Rotating dumbbells between palm-up and palm-down positions to target forearm rotators.'),
('Glutes', 'Barbell', 'Barbell Feet Elevated Figure Four Glute Bridge', 'A glute bridge with one ankle crossed over opposite knee and feet elevated.'),
('Glutes', 'Barbell', 'Barbell Feet Elevated Glute Bridge', 'A glute bridge with feet elevated on bench for increased range of motion.'),
('Glutes', 'Barbell', 'Barbell Feet Elevated Single Leg Glute Bridge', 'A unilateral glute bridge with active foot elevated for greater challenge.'),
('Glutes', 'Barbell', 'Barbell Feet Elevated Staggered Glute Bridge', 'A glute bridge with feet elevated and one foot forward for asymmetrical challenge.'),
('Glutes', 'Barbell', 'Barbell Figure Four Heels Elevated Hip Thrust', 'A hip thrust with one ankle crossed over opposite knee and heels elevated.'),
('Glutes', 'Barbell', 'Barbell Figure Four Hip Thrust', 'A hip thrust with one ankle crossed over opposite knee to target outer glute.'),
('Glutes', 'Barbell', 'Barbell Glute Bridge', 'A supine hip extension exercise with barbell across hips to target glutes.'),
('Glutes', 'Barbell', 'Barbell Heels Elevated Hip Thrust', 'A hip thrust with heels elevated to increase range of motion at hip joint.'),
('Glutes', 'Barbell', 'Barbell Hip Thrust', 'A supine hip extension exercise with shoulders elevated and barbell across hips.'),
('Glutes', 'Barbell', 'Barbell Single Leg Heels Elevated Hip Thrust', 'A unilateral hip thrust with heel elevated for increased range of motion.'),
('Glutes', 'Barbell', 'Barbell Single Leg Hip Thrust', 'A unilateral hip thrust to isolate one side for balanced development.'),
('Glutes', 'Barbell', 'Landmine Glute Kick Back', 'A standing hip extension exercise using landmine for resistance.'),
('Glutes', 'Barbell', 'Landmine Single Leg Glute Bridge', 'A unilateral glute bridge using landmine for resistance.'),
('Glutes', 'Bodyweight', 'Bodyweight Feet Elevated Figure Four Glute Bridge', 'A glute bridge with one ankle crossed over opposite knee and feet elevated.'),
('Glutes', 'Bodyweight', 'Bodyweight Feet Elevated Glute Bridge', 'A glute bridge with feet elevated on bench for increased range of motion.'),
('Glutes', 'Bodyweight', 'Bodyweight Feet Elevated Single Leg Glute Bridge', 'A unilateral glute bridge with active foot elevated for greater challenge.'),
('Glutes', 'Bodyweight', 'Bodyweight Feet Elevated Staggered Glute Bridge', 'A glute bridge with feet elevated and one foot forward for asymmetrical challenge.'),
('Glutes', 'Bodyweight', 'Bodyweight Figure Four Heels Elevated Hip Thrust', 'A hip thrust with one ankle crossed over opposite knee and heels elevated.'),
('Glutes', 'Bodyweight', 'Bodyweight Heels Elevated Hip Thrust', 'A hip thrust with heels elevated to increase range of motion at hip joint.'),
('Glutes', 'Bodyweight', 'Bodyweight Hip Abduction', 'A side-lying or standing leg raise targeting gluteus medius.'),
('Glutes', 'Bodyweight', 'Bodyweight Single Leg Heels Elevated Hip Thrust', 'A unilateral hip thrust with heel elevated for increased range of motion.'),
('Glutes', 'Bodyweight', 'Glute Bridge', 'A supine hip extension exercise to target glutes and posterior chain.'),
('Glutes', 'Bodyweight', 'Glute Bridge Eccentric Unilateral', 'A single-leg glute bridge focusing on slow lowering phase.'),
('Glutes', 'Bodyweight', 'Glute Bridge Isometric Hold Single Alternate', 'A static hold glute bridge alternating between legs.'),
('Glutes', 'Bodyweight', 'Kickbacks', 'A quadruped hip extension exercise targeting glutes directly.'),
('Glutes', 'Bodyweight', 'Single Leg Glute Bridge', 'A unilateral glute bridge to isolate one side for balanced development.'),
('Glutes', 'Cables', 'Cable Quadruped Hip Abduction', 'A four-point kneeling leg raise to side using cable resistance.'),
('Glutes', 'Cables', 'Cable Standing Glute Kickback', 'A standing hip extension using cable ankle attachment.'),
('Glutes', 'Cables', 'Cable Standing Hip Abduction', 'A standing leg raise to side using cable ankle attachment.'),
('Glutes', 'Cables', 'Cable Standing Hip Adduction', 'A standing leg pull inward across body using cable ankle attachment.'),
('Glutes', 'Dumbbells', 'Dumbbell Feet Elevated Figure Four Glute Bridge', 'A glute bridge with figure four position and feet elevated holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Feet Elevated Glute Bridge', 'A glute bridge with feet elevated on bench holding dumbbell across hips.'),
('Glutes', 'Dumbbells', 'Dumbbell Feet Elevated Single Leg Glute Bridge', 'A single-leg glute bridge with foot elevated holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Feet Elevated Staggered Glute Bridge', 'A staggered-foot glute bridge with feet elevated holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Figure Four Glute Bridge', 'A glute bridge with one ankle crossed over opposite knee holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Figure Four Heels Elevated Hip Thrust', 'A figure four hip thrust with heels elevated holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Figure Four Hip Thrust', 'A hip thrust with one ankle crossed over opposite knee holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Glute Bridge', 'A glute bridge with dumbbell positioned across hips for resistance.'),
('Glutes', 'Dumbbells', 'Dumbbell Heels Elevated Hip Thrust', 'A hip thrust with heels elevated holding dumbbell across hips.'),
('Glutes', 'Dumbbells', 'Dumbbell Hip Thrust', 'A hip thrust holding dumbbell across hips for resistance.'),
('Glutes', 'Dumbbells', 'Dumbbell Single Leg Glute Bridge', 'A unilateral glute bridge holding dumbbell across hip.'),
('Glutes', 'Dumbbells', 'Dumbbell Single Leg Heels Elevated Hip Thrust', 'A single-leg hip thrust with heel elevated holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Single Leg Hip Thrust', 'A unilateral hip thrust holding dumbbell across hip.'),
('Glutes', 'Dumbbells', 'Dumbbell Staggered Glute Bridge', 'A glute bridge with feet in staggered position holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Staggered Hip Thrust', 'A hip thrust with feet in staggered position holding dumbbell.'),
('Glutes', 'Dumbbells', 'Dumbbell Standing Hip Abduction', 'A standing leg raise to side while holding dumbbell for resistance.'),
('Glutes', 'Machine', 'Machine Hip Abduction', 'A seated or standing machine targeting gluteus medius with leg movement outward.'),
('Glutes', 'Machine', 'Machine Hip And Glute Abduction', 'A machine exercise moving legs outward to target gluteus medius.'),
('Glutes', 'Machine', 'Machine Hip And Glute Kickback', 'A machine exercise extending leg backward to target glutes.'),
('Glutes', 'Machine', 'Machine Hip Thrust', 'A hip thrust using specialized machine for consistent resistance curve.'),
('Glutes', 'Smith Machine', 'Smith Machine Glute Kickback', 'A hip extension exercise using Smith machine for resistance and guidance.'),
('Glutes', 'Smith Machine', 'Smith Machine Hip Thrust', 'A hip thrust using Smith machine bar across hips for resistance.'),
('Glutes', 'Smith Machine', 'Smith Machine Single Leg Hip Thrust', 'A unilateral hip thrust using Smith machine bar for resistance.'),
('Hamstrings', 'Barbell', 'Barbell Stiff Leg Deadlifts', 'A hip-hinge movement with minimal knee bend to target hamstrings and glutes.'),
('Hamstrings', 'Barbell', 'Landmine Romanian Deadlift', 'A Romanian deadlift using landmine for resistance and guidance.'),
('Hamstrings', 'Barbell', 'Landmine Single Leg Romanian Deadlift', 'A unilateral Romanian deadlift using landmine for balance assistance.'),
('Hamstrings', 'Barbell', 'Landmine Staggered Romanian Deadlift', 'A Romanian deadlift with feet staggered using landmine for guidance.'),
('Hamstrings', 'Barbell', 'Landmine Sumo Deadlift', 'A wide-stance deadlift using landmine for resistance pattern.'),
('Hamstrings', 'Bodyweight', 'Bodyweight Reverse Lunge', 'A backward lunge targeting hamstrings and glutes without added weight.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl 1 Supine Single Leg Slider', 'A single-leg hamstring curl lying on back using slider under foot.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl 2 Supine Single Leg Slider', 'A variation of single-leg hamstring curl with different positioning.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl Eccentric Supine Bilateral Sliders', 'A two-leg hamstring curl focusing on slow lowering phase.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl Standing Bodyweight Single Leg', 'A standing single-leg curl using resistance band or cable.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl Standing Isometric Bodyweight Single Leg', 'A static hold of standing leg curl for hamstring development.'),
('Hamstrings', 'Bodyweight', 'Hamstring Curl Supine Bilateral Slider', 'A two-leg hamstring curl lying on back using sliders under both feet.'),
('Hamstrings', 'Bodyweight', 'Nordic Hamstring Curl', 'A partner or anchored exercise lowering torso forward using hamstrings as brake.'),
('Hamstrings', 'Bodyweight', 'Hamstring Bridge Isometric Open Angle', 'A static bridge with legs wider than hip width for inner hamstring emphasis.'),
('Hamstrings', 'Bodyweight', 'Hamstring Bridge With Elevated Legs Box Bilateral', 'A glute bridge with both legs elevated on box targeting hamstrings.'),
('Hamstrings', 'Bodyweight', 'Hamstring Bridge With Elevated Legs Box Unilateral', 'A single-leg glute bridge with active leg elevated on box.'),
('Hamstrings', 'Bodyweight', 'Single Legged Romanian Deadlifts', 'A unilateral hip-hinge movement developing balance and posterior chain.'),
('Hamstrings', 'Cables', 'Cable Hamstring Curl', 'A hamstring curl using cable ankle attachment for resistance.'),
('Hamstrings', 'Cables', 'Cable Seated Leg Curl', 'A seated hamstring curl using cable attachment for resistance.'),
('Hamstrings', 'Cables', 'Cable Single Leg Laying Leg Curl', 'A prone single-leg curl using cable attachment for resistance.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Leg Curl', 'A hamstring curl holding dumbbell between feet for resistance.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Cross Body Romanian Deadlift', 'A Romanian deadlift with dumbbell moved across to opposite foot.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Romanian Deadlift', 'A hip-hinge movement with minimal knee bend using dumbbells.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Single Leg Single Arm Deadlift', 'A unilateral deadlift using single dumbbell for diagonal loading.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Single Leg Stiff Leg Deadlift', 'A unilateral Romanian deadlift using dumbbells for resistance.'),
('Hamstrings', 'Dumbbells', 'Dumbbell Staggered Deadlift', 'A deadlift with feet in staggered position using dumbbells.'),
('Hamstrings', 'Machine', 'Glute Ham Raise', 'A posterior chain exercise using specialized bench targeting hamstrings and glutes.'),
('Hamstrings', 'Machine', 'Machine Hamstring Curl', 'A prone hamstring curl using specialized machine for consistent resistance.'),
('Hamstrings', 'Machine', 'Machine Seated Leg Curl', 'A seated hamstring curl using specialized machine for consistent resistance.'),
('Hamstrings', 'Machine', 'Seated Leg Curl', 'A seated hamstring curl using weight stack for consistent resistance.'),
('Lower_Back', 'Barbell', 'Barbell Coan Deadlift', 'A deadlift variation with wider stance but narrower than sumo deadlift.'),
('Lower_Back', 'Barbell', 'Barbell High Bar Good Morning', 'A hip-hinge movement with bar positioned high on traps.'),
('Lower_Back', 'Barbell', 'Barbell Low Bar Good Morning', 'A hip-hinge movement with bar positioned lower on back.'),
('Lower_Back', 'Barbell', 'Barbell Low Bar Squat', 'A squat with bar positioned lower on back for increased hip engagement.'),
('Lower_Back', 'Barbell', 'Barbell Pause Box Squat', 'A squat to box with pause at bottom position for strength development.'),
('Lower_Back', 'Barbell', 'Barbell Pause Squat', 'A squat with deliberate pause at bottom position for strength development.'),
('Lower_Back', 'Barbell', 'Barbell Reverse Deadlift', 'A deadlift starting from top position and lowering to floor.'),
('Lower_Back', 'Barbell', 'Barbell Romanian Deadlift', 'A hip-hinge movement with minimal knee bend targeting hamstrings and posterior chain.'),
('Lower_Back', 'Barbell', 'Barbell Single Leg Deadlift', 'A unilateral hip-hinge movement developing balance and posterior chain.'),
('Lower_Back', 'Barbell', 'Barbell Snatch Grip Deadlift', 'A deadlift using wide grip to increase range of motion and back engagement.'),
('Lower_Back', 'Barbell', 'Barbell Snatch Grip Romanian Deadlift', 'A Romanian deadlift using wide grip for increased upper back activation.'),
('Lower_Back', 'Barbell', 'Barbell Staggered Deadlift', 'A deadlift with feet in staggered position for asymmetrical challenge.'),
('Lower_Back', 'Barbell', 'Barbell Suitcase Deadlift', 'A unilateral deadlift holding weight on one side to target obliques.'),
('Lower_Back', 'Barbell', 'Barbell Sumo Deadlift', 'A deadlift with wide stance and hands inside knees targeting inner thighs and back.'),
('Lower_Back', 'Barbell', 'Barbell Zercher Good Morning', 'A good morning with bar held in crook of elbows for different stimulus.'),
('Lower_Back', 'Barbell', 'Barbell Zercher Squat', 'A squat with bar held in crook of elbows for upright torso position.'),
('Lower_Back', 'Barbell', 'Barbell Deadlift', 'A fundamental hip-hinge movement lifting barbell from floor to hip level.'),
('Lower_Back', 'Barbell', 'Landmine Snatch', 'An explosive Olympic lifting variation using landmine for guidance.'),
('Lower_Back', 'Bodyweight', 'Good Mornings', 'A hip-hinge movement without weight to develop posterior chain awareness.'),
('Lower_Back', 'Bodyweight', 'Supermans', 'A prone back extension lifting arms and legs simultaneously.'),
('Lower_Back', 'Cables', 'Cable Bar Romanian Deadlift', 'A Romanian deadlift using cable resistance for different force curve.'),
('Lower_Back', 'Cables', 'Cable Bar Staggered Romanian Deadlift', 'A staggered-stance Romanian deadlift using cable resistance.'),
('Lower_Back', 'Cables', 'Cable Bench Straight Leg Kickback', 'A prone hip extension on bench using cable ankle attachment.'),
('Lower_Back', 'Cables', 'Cable Elevated Deadlift', 'A deadlift starting from elevated position using cable resistance.'),
('Lower_Back', 'Cables', 'Cable Goblet Squat', 'A squat using cable handle held at chest in goblet position.'),
('Lower_Back', 'Cables', 'Cable Incline Bench Straight Leg Kickback', 'A hip extension on inclined bench using cable ankle attachment.'),
('Lower_Back', 'Cables', 'Cable Pull Through', 'A hip-hinge exercise pulling cable between legs targeting glutes and hamstrings.'),
('Lower_Back', 'Cables', 'Cable Single Leg Deadlift', 'A unilateral deadlift using cable resistance for different force curve.'),
('Lower_Back', 'Cables', 'Cable Standing Mid Kickback', 'A standing hip extension using cable targeting mid glute region.'),
('Lower_Back', 'Cables', 'Cable Standing Straight Leg Glute Glute Kickback', 'A standing straight-leg hip extension using cable resistance.'),
('Lower_Back', 'Cables', 'Cable Standing Straight Leg Mid Kickback', 'A variation of standing kickback targeting mid glute region with straight leg.'),
('Lower_Back', 'Cables', 'Cable Zercher Good Morning', 'A good morning with cable held in crook of elbows.'),
('Lower_Back', 'Cables', 'Cable Zercher Squat', 'A squat with cable handle held in crook of elbows.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Front Rack Pause Squat', 'A squat with pause at bottom holding dumbbells at shoulder level.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Goblet Good Morning', 'A hip-hinge movement holding dumbbell in goblet position at chest.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Sumo Squat', 'A wide-stance squat using dumbbells for resistance.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Superman', 'A prone back extension lifting arms and legs with dumbbells for added resistance.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Superman Hold', 'An isometric hold of the superman position with dumbbells.'),
('Lower_Back', 'Dumbbells', 'Dumbbell Swing', 'A dynamic hip-hinge swinging dumbbell between legs and up to chest height.'),
('Lower_Back', 'Machine', 'Machine 45 Degree Back Extension', 'A posterior chain exercise using angled bench for back development.'),
('Lower_Back', 'Smith Machine', 'Smith Machine Romanian Deadlift', 'A Romanian deadlift using Smith machine for fixed bar path.'),
('Lower_Back', 'Smith Machine', 'Smith Machine Staggered Deadlift', 'A staggered-stance deadlift using Smith machine for stability.'),
('Lower_Back', 'Smith Machine', 'Smith Machine Sumo Romanian Deadlift', 'A wide-stance Romanian deadlift using Smith machine for guidance.'),
('Quadriceps', 'Barbell', 'Barbell Front Squat Olympic', 'A front squat using clean grip position with elbows high and torso upright.'),
('Quadriceps', 'Barbell', 'Barbell Landmine Sissy Squat', 'A quad-focused squat variation using landmine for balance assistance.'),
('Quadriceps', 'Barbell', 'Barbell Front Squat Bodybuilding', 'A front squat variation with elbows high and close stance for quad emphasis.'),
('Quadriceps', 'Barbell', 'Barbell Front Squat With Straps', 'A front squat using lifting straps to hold bar for wrist comfort.'),
('Quadriceps', 'Barbell', 'Barbell Heels Up Back Squat', 'A back squat with heels elevated to shift emphasis to quads.'),
('Quadriceps', 'Barbell', 'Barbell Heels Up Front Squat', 'A front squat with heels elevated to maximize quad engagement.'),
('Quadriceps', 'Barbell', 'Barbell High Bar Squat', 'A squat with bar positioned high on traps for more upright torso.'),
('Quadriceps', 'Barbell', 'Barbell Squat', 'A fundamental lower body exercise lowering body by bending knees and hips.'),
('Quadriceps', 'Barbell', 'Barbell Tap Pause Squat', 'A squat with brief pause at bottom position tapping floor with glutes.'),
('Quadriceps', 'Barbell', 'Landmine Hack Squat', 'A squat variation with landmine positioned behind body.'),
('Quadriceps', 'Barbell', 'Landmine Squat', 'A squat variation holding end of landmine bar for resistance.'),
('Quadriceps', 'Barbell', 'Barbell Bulgarian Split Squat', 'A unilateral squat with rear foot elevated on bench targeting glutes and quads.'),
('Quadriceps', 'Barbell', 'Barbell Curtsy Lunge', 'A lunge stepping behind and across body to target gluteus medius.'),
('Quadriceps', 'Barbell', 'Barbell Forward Lunge', 'A bilateral lower body exercise stepping forward into lunge position.'),
('Quadriceps', 'Barbell', 'Barbell Front Rack Step Up', 'A step up holding barbell in front rack position to target glutes and quads.'),
('Quadriceps', 'Barbell', 'Barbell Kickstand Squat', 'A squat with one foot slightly behind in kickstand position for asymmetrical loading.'),
('Quadriceps', 'Barbell', 'Barbell Lateral Lunge', 'A lunge stepping directly to side to target adductors and gluteus medius.'),
('Quadriceps', 'Barbell', 'Barbell Reverse Lunge', 'A lunge stepping backward to target glutes and preserve knee health.'),
('Quadriceps', 'Barbell', 'Barbell Side Step Up', 'A lateral step up onto platform targeting glutes and hip abductors.'),
('Quadriceps', 'Barbell', 'Barbell Split Squat', 'A stationary lunge position with both feet in fixed positions.'),
('Quadriceps', 'Barbell', 'Barbell Step Up', 'A unilateral exercise stepping onto elevated surface with barbell.'),
('Quadriceps', 'Barbell', 'Barbell Step Up Balance', 'A step up with momentary balance on platform to increase stability challenge.'),
('Quadriceps', 'Barbell', 'Landmine Alternating Lunge And Twist', 'A lunge with rotational component using landmine for resistance.'),
('Quadriceps', 'Barbell', 'Landmine Alternating Lunge To Chest Press', 'A combination exercise linking lunge with pressing movement.'),
('Quadriceps', 'Barbell', 'Landmine Curtsy Lunge', 'A curtsy lunge using landmine for resistance and stability guidance.'),
('Quadriceps', 'Barbell', 'Landmine Goblet Curtsy Lunge', 'A curtsy lunge holding end of landmine bar in goblet position.'),
('Quadriceps', 'Barbell', 'Landmine Goblet Lateral Lunge', 'A lateral lunge holding end of landmine bar in goblet position.'),
('Quadriceps', 'Barbell', 'Landmine Lateral Lunge', 'A side lunge using landmine for resistance and movement guidance.'),
('Quadriceps', 'Barbell', 'Landmine Lunge', 'A forward lunge using landmine for resistance and stability.'),
('Quadriceps', 'Barbell', 'Landmine Lunge To Overhead Press', 'A combination exercise linking lunge with overhead press.'),
('Quadriceps', 'Barbell', 'Landmine Rotational Lift To Press', 'A functional movement from low to high position with rotation.'),
('Quadriceps', 'Barbell', 'Landmine Thruster', 'A combination squat and overhead press using landmine apparatus.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Reverse Step Up', 'A step up moving backward onto platform to target quads.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Squat', 'A fundamental lower body exercise using only body weight.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Box Squat', 'A squat sitting back to box or bench for consistent depth.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Heels Up Squat', 'A squat with heels elevated to shift emphasis to quads.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Pop Squat', 'A plyometric squat jumping outward to wider stance and back in.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Pulse Squat', 'A squat with small range partial repetitions at bottom position.'),
('Quadriceps', 'Bodyweight', 'In And Out Jump Squat', 'A plyometric squat alternating between narrow and wide foot positions.'),
('Quadriceps', 'Bodyweight', 'Jump Squats', 'A plyometric squat with explosive jump at top of movement.'),
('Quadriceps', 'Bodyweight', 'Assisted Bulgarian Split Squat', 'A split squat with rear foot elevated using support for assistance.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Alternating Curtsy Lunge', 'A curtsy lunge alternating sides for balanced development.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Alternating Jump Lunge', 'A plyometric exercise alternating lunge positions in mid-air.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Alternating Lateral Lunge', 'A side lunge alternating sides for balanced development.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Alternating Reverse Lunges', 'A backward lunge alternating sides for balanced development.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Kickstand Squat', 'A squat with one foot slightly behind in kickstand position for asymmetrical loading.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Lateral Lunge Jump', 'A plyometric side lunge with jump between sides for explosive power.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Swing Lunge', 'A dynamic lunge switching legs in swinging motion for mobility.'),
('Quadriceps', 'Bodyweight', 'Bodyweight Swingthrough Lunge', 'A lunge transitioning through center position for fluid movement.'),
('Quadriceps', 'Bodyweight', 'Bulgarian Split Squat', 'A unilateral squat with rear foot elevated on bench targeting glutes and quads.'),
('Quadriceps', 'Bodyweight', 'Curtsy Lunge', 'A lunge stepping behind and across body to target gluteus medius.'),
('Quadriceps', 'Bodyweight', 'Depth Jump', 'A plyometric exercise stepping off box and immediately jumping upward for reactive strength.'),
('Quadriceps', 'Bodyweight', 'Forward Lunge', 'A bilateral lower body exercise stepping forward into lunge position.'),
('Quadriceps', 'Bodyweight', 'Forward Lunges', 'Sequential forward lunges alternating legs for balanced development.'),
('Quadriceps', 'Bodyweight', 'Lateral Lunge', 'A lunge stepping directly to side to target adductors and gluteus medius.'),
('Quadriceps', 'Bodyweight', 'Lunge Alternate', 'Alternating between right and left lunges in sequence.'),
('Quadriceps', 'Bodyweight', 'Lunge Walking', 'Moving forward performing consecutive lunges alternating legs.'),
('Quadriceps', 'Bodyweight', 'Pole Overhead Squat', 'A squat holding pole or broomstick overhead for alignment training.'),
('Quadriceps', 'Bodyweight', 'Seated Box Jump', 'A plyometric jump starting from seated position for increased difficulty.'),
('Quadriceps', 'Bodyweight', 'Side Lunges', 'Sequential lateral lunges alternating sides for balanced development.'),
('Quadriceps', 'Bodyweight', 'Single Leg Box Jump', 'A plyometric exercise jumping onto elevated surface with one foot.'),
('Quadriceps', 'Bodyweight', 'Split Squat', 'A stationary lunge position with both feet in fixed positions.'),
('Quadriceps', 'Bodyweight', 'Step Up Knee Drive', 'A step up with knee drive at top position for increased glute activation.'),
('Quadriceps', 'Bodyweight', 'Box Jump', 'A plyometric exercise jumping onto elevated surface with both feet.'),
('Quadriceps', 'Cables', 'Cable Seated Leg Extension', 'A seated knee extension using cable attachment for resistance.'),
('Quadriceps', 'Cables', 'Cable Standing Leg Extension', 'A standing knee extension using cable ankle attachment.'),
('Quadriceps', 'Cables', 'Cable Split Squat', 'A split squat using cable resistance for varied load pattern.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Leg Extension', 'A knee extension exercise using dumbbell for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Front Rack Squat', 'A squat holding dumbbells at shoulder level for front-loaded resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Pulse Squat', 'A partial range squat with small pulses holding dumbbell at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Squat', 'A squat holding dumbbell vertically against chest for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Heels Up Goblet Squat', 'A goblet squat with heels elevated to target quads.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Heels Up Narrow Goblet Squat', 'A narrow-stance goblet squat with heels elevated for quad emphasis.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Bulgarian Split Squat', 'A split squat with rear foot elevated holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Forward Lunge', 'A forward lunge holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Front Rack Step Up', 'A step up holding dumbbells at shoulder level for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Bulgarian Split Squat', 'A split squat with rear foot elevated holding dumbbell in goblet position.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Curtsy Lunge', 'A curtsy lunge holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Forward Lunge', 'A forward lunge holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Lateral Lunge', 'A side lunge holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Reverse Lunge', 'A backward lunge holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Side Step Up', 'A lateral step up holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Split Squat', 'A split squat holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Goblet Step Up', 'A step up holding dumbbell in goblet position at chest.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Kickstand Squat', 'A squat with one foot slightly back holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Lateral Lunge Reach', 'A side lunge with dumbbell reached toward floor for increased range.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Offset Squat', 'A squat holding single dumbbell on one side for anti-lateral flexion.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Overhead Squat', 'A squat holding dumbbells overhead challenging stability and mobility.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Reverse Lunge', 'A backward lunge holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Side Step Up', 'A lateral step up holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Single Arm Front Rack Step Up', 'A step up holding single dumbbell at shoulder level.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Single Arm Step Up', 'A step up holding single dumbbell for unilateral loading.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Split Squat', 'A stationary lunge position holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Step Up', 'A step up onto elevated surface holding dumbbells for resistance.'),
('Quadriceps', 'Dumbbells', 'Dumbbell Thruster', 'A combination squat and overhead press with dumbbells.'),
('Quadriceps', 'Dumbbells', 'Single Arm Overhead Squat', 'A squat holding single dumbbell overhead for asymmetrical challenge.'),
('Quadriceps', 'Machine', 'Machine Goblet Sissy Squat', 'A sissy squat using specialized machine with goblet weight position.'),
('Quadriceps', 'Machine', 'Machine Hip Adduction', 'A machine exercise moving legs inward to target inner thighs.'),
('Quadriceps', 'Machine', 'Machine Hip And Glute Adduction', 'A machine exercise moving legs inward to target adductors and glutes.'),
('Quadriceps', 'Machine', 'Machine Leg Extension', 'A seated knee extension using specialized machine for consistent resistance.'),
('Quadriceps', 'Machine', 'Machine Sissy Squat', 'A quad-focused squat variation using specialized machine for support.'),
('Quadriceps', 'Machine', 'Machine Hack Squat', 'A squat variation using specialized machine with angled back support.'),
('Quadriceps', 'Machine', 'Machine Horizontal Leg Press', 'A leg press with horizontal movement pattern targeting quadriceps and glutes.'),
('Quadriceps', 'Machine', 'Machine Horizontal Sissy Leg Press', 'A leg press with feet high on platform for greater quad emphasis.'),
('Quadriceps', 'Machine', 'Machine Leg Press', 'A compound lower body press using machine for controlled movement.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Sissy Squat', 'A sissy squat using Smith machine for balance assistance.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Leg Press', 'A leg press variation using Smith machine with body positioned under bar.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Narrow Stance Squat', 'A squat with close foot position using Smith machine for stability.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Reverse Lunge', 'A backward lunge using Smith machine bar for resistance and stability.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Split Squat', 'A stationary lunge using Smith machine bar for resistance and stability.'),
('Quadriceps', 'Smith Machine', 'Smith Machine Squat', 'A squat using Smith machine for fixed vertical bar path.'),
('Shoulders', 'Barbell', 'Barbell Behind The Neck Seated Overhead Press', 'A seated overhead press with bar positioned behind neck.'),
('Shoulders', 'Barbell', 'Barbell Front Raise', 'A shoulder exercise raising barbell forward to eye level.'),
('Shoulders', 'Barbell', 'Barbell Overhead Press', 'A standing exercise pressing barbell from shoulders to overhead.'),
('Shoulders', 'Barbell', 'Barbell Upright Row', 'A vertical pull exercise raising barbell to chin height with elbows leading.'),
('Shoulders', 'Barbell', 'Barbell Z Press', 'A seated overhead press performed on floor with legs extended forward.'),
('Shoulders', 'Barbell', 'Landmine Alternating Single Arm Press', 'A unilateral overhead press using landmine alternating arms.'),
('Shoulders', 'Barbell', 'Landmine Half Kneeling Single Arm Overhead Press', 'A unilateral press in half-kneeling position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Kneeling Alternating Overhead Press', 'An alternating overhead press in kneeling position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Kneeling Overhead Press', 'A bilateral overhead press in kneeling position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Lateral Raise', 'A shoulder abduction exercise using landmine for resistance.'),
('Shoulders', 'Barbell', 'Landmine Overhead Press', 'A bilateral overhead press using landmine apparatus.'),
('Shoulders', 'Barbell', 'Landmine Seated Alternating Overhead Press', 'An alternating overhead press in seated position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Seated Overhead Press', 'A bilateral overhead press in seated position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Seated Single Arm Overhead Press', 'A unilateral press in seated position using landmine.'),
('Shoulders', 'Barbell', 'Landmine Single Arm Overhead Press', 'A unilateral overhead press using landmine apparatus.'),
('Shoulders', 'Barbell', 'Landmine Single Arm Push Press', 'A unilateral overhead press using leg drive with landmine.'),
('Shoulders', 'Barbell', 'Landmine Single Arm Staggered Overhead Press', 'A unilateral press in staggered stance using landmine.'),
('Shoulders', 'Barbell', 'Landmine Split Jerk', 'An explosive overhead movement with split leg position using landmine.'),
('Shoulders', 'Bodyweight', 'Backward Arm Circle', 'A shoulder mobility exercise moving arms in backward circular motion.'),
('Shoulders', 'Bodyweight', 'Forward Arm Circle', 'A shoulder mobility exercise moving arms in forward circular motion.'),
('Shoulders', 'Bodyweight', 'Ring Rear Delt Fly', 'A horizontal shoulder abduction using gymnastic rings targeting posterior deltoids.'),
('Shoulders', 'Bodyweight', 'Ring Standing Pushup', 'A chest press movement using unstable gymnastic rings.'),
('Shoulders', 'Cables', 'Cable High Internally Rotated Reverse Fly', 'A rear deltoid exercise with internally rotated shoulders using cables.'),
('Shoulders', 'Cables', 'Cable High Reverse Fly', 'A horizontal shoulder abduction using high cable position for posterior deltoids.'),
('Shoulders', 'Cables', 'Cable High Single Arm Rear Delt Fly', 'A unilateral rear deltoid exercise using high cable position.'),
('Shoulders', 'Cables', 'Cable Low Bilateral Lateral Raise', 'A shoulder abduction exercise using low cable position.'),
('Shoulders', 'Cables', 'Cable Low Single Arm Lateral Raise', 'A unilateral shoulder abduction using low cable position.'),
('Shoulders', 'Cables', 'Cable Overhead Press', 'A bilateral overhead press using cable resistance.'),
('Shoulders', 'Cables', 'Cable Rope Front Raise', 'A shoulder flexion exercise using rope attachment.'),
('Shoulders', 'Cables', 'Cable Rope Kneeling Face Pull', 'A specialized pull targeting rear deltoids and external rotators in kneeling position.'),
('Shoulders', 'Cables', 'Cable Rope Mid Lateral Raise', 'A shoulder abduction using middle pulley height with rope attachment.'),
('Shoulders', 'Cables', 'Cable Rope Single Arm Low Lateral Raise', 'A unilateral shoulder abduction using low cable with rope attachment.'),
('Shoulders', 'Cables', 'Cable Rope Upright Row', 'A vertical pull raising rope attachment to chin height with elbows leading.'),
('Shoulders', 'Cables', 'Cable Single Arm Internally Rotated High Reverse Fly', 'A unilateral rear deltoid exercise with internal rotation using high cable.'),
('Shoulders', 'Cables', 'Cable Upright Row', 'A vertical pull raising cable handle to chin height with elbows leading.'),
('Shoulders', 'Cables', 'Machine Face Pulls', 'A horizontal pull targeting rear deltoids and external rotators using cable station.'),
('Shoulders', 'Dumbbells', 'Dumbbell Alternating Arnold Press', 'An overhead press with rotational component alternating arms.'),
('Shoulders', 'Dumbbells', 'Dumbbell Alternating Overhead Press', 'An overhead press alternating arms for increased core engagement.'),
('Shoulders', 'Dumbbells', 'Dumbbell Arnold Press', 'An overhead press with rotational component from pronated to supinated grip.'),
('Shoulders', 'Dumbbells', 'Dumbbell Bayesian Lateral Raise', 'A lateral raise variation maintaining optimal resistance through movement.'),
('Shoulders', 'Dumbbells', 'Dumbbell Bent Arm Lateral Raise', 'A lateral raise keeping elbows slightly bent throughout movement.'),
('Shoulders', 'Dumbbells', 'Dumbbell Front Raise', 'A shoulder exercise raising dumbbell forward to eye level.'),
('Shoulders', 'Dumbbells', 'Dumbbell Internally Rotated Rear Delt Fly', 'A rear deltoid exercise with internal rotation for targeted development.'),
('Shoulders', 'Dumbbells', 'Dumbbell Lateral Raise', 'A shoulder abduction exercise raising dumbbells to sides to shoulder level.'),
('Shoulders', 'Dumbbells', 'Dumbbell Laying Reverse Fly', 'A prone rear deltoid exercise performed lying on bench.'),
('Shoulders', 'Dumbbells', 'Dumbbell Laying Reverse Fly Internally Rotated', 'A prone rear deltoid exercise with internal rotation for targeted development.'),
('Shoulders', 'Dumbbells', 'Dumbbell Neutral Alternating Overhead Press', 'An alternating overhead press using neutral grip for shoulder health.'),
('Shoulders', 'Dumbbells', 'Dumbbell Neutral Overhead Press', 'An overhead press using neutral grip for balanced shoulder development.'),
('Shoulders', 'Dumbbells', 'Dumbbell Neutral Seated Overhead Press', 'A seated overhead press using neutral grip for shoulder health.'),
('Shoulders', 'Dumbbells', 'Dumbbell Overhead Press', 'A standing exercise pressing dumbbells from shoulders to overhead.'),
('Shoulders', 'Dumbbells', 'Dumbbell Push Press', 'An overhead press using leg drive to generate momentum for heavier loads.'),
('Shoulders', 'Dumbbells', 'Dumbbell Rear Delt Fly', 'A bent-over exercise raising dumbbells laterally to target posterior deltoids.'),
('Shoulders', 'Dumbbells', 'Dumbbell Seated Arnold Press', 'A seated overhead press with rotational component.'),
('Shoulders', 'Dumbbells', 'Dumbbell Seated Overhead Press', 'A seated exercise pressing dumbbells from shoulders to overhead.'),
('Shoulders', 'Dumbbells', 'Dumbbell Seated Rear Delt Fly', 'A seated variation of rear deltoid fly for increased stability.'),
('Shoulders', 'Dumbbells', 'Dumbbell Shoulder External Rotation', 'A rotational exercise for rotator cuff targeting external rotators.'),
('Shoulders', 'Dumbbells', 'Dumbbell Single Arm Arnold Press', 'A unilateral overhead press with rotational component.'),
('Shoulders', 'Dumbbells', 'Dumbbell Single Arm Neutral Overhead Press', 'A unilateral overhead press using neutral grip for shoulder health.'),
('Shoulders', 'Dumbbells', 'Dumbbell Single Arm Overhead Press', 'A unilateral standing exercise pressing dumbbell overhead.'),
('Shoulders', 'Dumbbells', 'Dumbbell Single Arm Upright Row', 'A unilateral vertical pull raising dumbbell with elbow leading.'),
('Shoulders', 'Dumbbells', 'Dumbbell Standing Bayesian Lateral Raise', 'A standing lateral raise variation maintaining optimal resistance through arc.'),
('Shoulders', 'Dumbbells', 'Dumbbell Upright Row', 'A vertical pull raising dumbbells to chin height with elbows leading.'),
('Shoulders', 'Dumbbells', 'Internally Rotated Seated Rear Delt Fly', 'A seated rear deltoid exercise with internal rotation for targeted development.'),
('Shoulders', 'Dumbbells', 'Laying Lateral Raise', 'A supine shoulder abduction exercise for isolated medial deltoid work.'),
('Shoulders', 'Dumbbells', 'Seated Lateral Raise', 'A seated shoulder abduction exercise with more controlled form.'),
('Shoulders', 'Machine', 'Machine Neutral Overhead Press', 'A seated overhead press using neutral grip handles on specialized machine.'),
('Shoulders', 'Machine', 'Machine Overhand Overhead Press', 'A seated overhead press using pronated grip handles on specialized machine.'),
('Shoulders', 'Machine', 'Machine Overhand Row', 'A seated horizontal pull using pronated grip on specialized machine.'),
('Shoulders', 'Machine', 'Machine Reverse Fly', 'A posterior deltoid exercise using specialized machine for consistent resistance.'),
('Shoulders', 'Smith Machine', 'Smith Machine Seated Overhead Press', 'A seated overhead press using Smith machine for fixed bar path.'),
('Shoulders', 'Smith Machine', 'Smith Machine Upright Row', 'A vertical pull using Smith machine raising bar with elbows leading.'),
('Trapezius', 'Barbell', 'Barbell Deadlift', 'A fundamental hip-hinge movement lifting barbell from floor to hip level.'),
('Trapezius', 'Barbell', 'Barbell Shrug', 'A vertical shoulder elevation exercise to develop upper trapezius.'),
('Trapezius', 'Barbell', 'Barbell Silverback Shrug', 'A combination of partial row and shrug to target mid and upper trapezius.'),
('Trapezius', 'Bodyweight', 'Bodyweight Overhand Inverted Row', 'A horizontal pulling exercise using overhand grip to target upper back.'),
('Trapezius', 'Bodyweight', 'Bodyweight Pike Press', 'A vertical pressing movement in pike position targeting shoulders and trapezius.'),
('Trapezius', 'Bodyweight', 'Bodyweight Pike Shrug', 'A shrug performed in pike position for varied trapezius stimulation.'),
('Trapezius', 'Bodyweight', 'Bodyweight Standing Inverted Row', 'A horizontal pulling exercise using elevated bar and more upright body position.'),
('Trapezius', 'Bodyweight', 'Elevated Pike Press', 'A pike press with feet elevated to increase loading on upper body.'),
('Trapezius', 'Bodyweight', 'Elevated Pike Shoulder Shrug', 'A pike shrug with feet elevated for increased trapezius activation.'),
('Trapezius', 'Bodyweight', 'Inverted Row', 'A horizontal pulling exercise lying under bar targeting upper back.'),
('Trapezius', 'Bodyweight', 'Pull Ups', 'A vertical pulling exercise lifting body up to bar using overhand grip.'),
('Trapezius', 'Cables', 'Cable 30 Degree Shrug', 'A shrug performed at slight forward angle to target middle trapezius.'),
('Trapezius', 'Cables', 'Cable Silverback Shrug', 'A combination of partial row and shrug using cable for resistance.'),
('Trapezius', 'Cables', 'Cable Single Arm 30 Degree Shrug', 'A unilateral angled shrug targeting middle trapezius using cable.'),
('Trapezius', 'Cables', 'Cable Single Arm Rear Delt Row', 'A unilateral row targeting rear deltoid and trapezius using cable.'),
('Trapezius', 'Dumbbells', 'Dumbbell Laying 30 Degree Shrug', 'A prone shrug on incline bench targeting middle trapezius.'),
('Trapezius', 'Dumbbells', 'Dumbbell Laying Silverback Shrug', 'A prone combination of partial row and shrug on bench.'),
('Trapezius', 'Dumbbells', 'Dumbbell Row Bilateral', 'A bent-over row using dumbbells in both hands simultaneously.'),
('Trapezius', 'Dumbbells', 'Dumbbell Row Unilateral', 'A single-arm bent-over row supporting body with opposite arm.'),
('Trapezius', 'Dumbbells', 'Dumbbell Seated Rear Delt Row', 'A seated row targeting posterior deltoids and trapezius.'),
('Trapezius', 'Dumbbells', 'Dumbbell Seated Shrug', 'A seated shoulder elevation to isolate trapezius without leg assistance.'),
('Trapezius', 'Dumbbells', 'Dumbbell Shrug', 'A vertical shoulder elevation using dumbbells to develop upper trapezius.'),
('Trapezius', 'Dumbbells', 'Dumbbell Silverback Shrug', 'A standing combination of partial row and shrug using dumbbells.'),
('Trapezius', 'Machine', 'Smith Machine Standing Shrugs', 'A vertical shoulder elevation using Smith machine for fixed bar path.'),
('Triceps', 'Barbell', 'Barbell Laying Triceps Extensions', 'A supine elbow extension exercise targeting triceps, also known as skullcrushers.'),
('Triceps', 'Barbell', 'Barbell Overhead Tricep Extension', 'A vertical elbow extension exercise with barbell overhead.'),
('Triceps', 'Barbell', 'Barbell Skullcrusher', 'A supine elbow extension exercise lowering barbell toward forehead.'),
('Triceps', 'Barbell', 'Landmine Lying Tricep Extension', 'A supine elbow extension using landmine apparatus.'),
('Triceps', 'Barbell', 'Landmine Single Arm Chest Press', 'A unilateral pressing movement using landmine for resistance.'),
('Triceps', 'Bodyweight', 'Bench Dips', 'A bodyweight elbow extension exercise using bench for support.'),
('Triceps', 'Bodyweight', 'Bodyweight Box Assisted Dips', 'A vertical pressing exercise with partial weight supported on box.'),
('Triceps', 'Bodyweight', 'Bodyweight Clapping Push Up', 'An explosive pushup with mid-air hand clap requiring significant tricep strength.'),
('Triceps', 'Bodyweight', 'Bodyweight Diamond Knee Push Ups', 'A modified pushup with hands in diamond position targeting triceps.'),
('Triceps', 'Bodyweight', 'Bodyweight Elevated Push Up', 'A pushup with hands elevated to decrease loading for progression.'),
('Triceps', 'Bodyweight', 'Bodyweight Explosive Push Up', 'A plyometric pushup with emphasis on explosive concentric phase.'),
('Triceps', 'Bodyweight', 'Bodyweight Incline Knee Push Up', 'A modified pushup with hands elevated and knees on ground for beginners.'),
('Triceps', 'Bodyweight', 'Bodyweight Knee Push Ups', 'A modified pushup with knees on ground to decrease loading.'),
('Triceps', 'Bodyweight', 'Bodyweight Knee Tricep Extension', 'A tricep extension performed on knees with bodyweight resistance.'),
('Triceps', 'Bodyweight', 'Bodyweight Tricep Extension', 'A bodyweight elbow extension performed in prone position.'),
('Triceps', 'Bodyweight', 'Box Dips', 'A bodyweight elbow extension between elevated boxes or platforms.'),
('Triceps', 'Bodyweight', 'Decline Push Up', 'A pushup with feet elevated to increase loading on upper body.'),
('Triceps', 'Bodyweight', 'Diamond Push Ups', 'A pushup with hands in diamond position directly under chest to target triceps.'),
('Triceps', 'Bodyweight', 'Dips Narrow Elbows', 'A vertical pressing exercise with elbows kept close to body for tricep emphasis.'),
('Triceps', 'Bodyweight', 'Incline Push Up', 'A pushup with hands elevated to decrease loading for progression.'),
('Triceps', 'Bodyweight', 'Parralel Bar Dips', 'A vertical pressing exercise between parallel bars targeting triceps and chest.'),
('Triceps', 'Bodyweight', 'Ring Skullcrusher', 'A tricep extension performed using gymnastic rings for instability challenge.'),
('Triceps', 'Bodyweight', 'Ring Standing Archer Pushup', 'A unilateral pushup variation using rings with one arm extended.'),
('Triceps', 'Cables', 'Cable Bar Pushdown', 'A tricep extension pushing bar attachment downward against cable resistance.'),
('Triceps', 'Cables', 'Cable Bar Reverse Grip Pushdown', 'A tricep extension using supinated grip pushing bar downward.'),
('Triceps', 'Cables', 'Cable Cross Pushdown', 'A tricep extension crossing arms during downward movement for inner head emphasis.'),
('Triceps', 'Cables', 'Cable Rope Overhead Tricep Extension', 'A tricep extension with arms overhead using rope attachment.'),
('Triceps', 'Cables', 'Cable Rope Pushdown', 'A tricep extension pushing rope attachment downward against cable resistance.'),
('Triceps', 'Cables', 'Cable Rope Skullcrusher', 'A supine tricep extension using rope attachment for increased range of motion.'),
('Triceps', 'Cables', 'Cable Single Arm Cross Pushdown', 'A unilateral tricep extension with crossing motion for inner head emphasis.'),
('Triceps', 'Cables', 'Cable Single Arm Rope Pushdown', 'A unilateral tricep extension using rope attachment.'),
('Triceps', 'Cables', 'Cable Single Arm Skullcrusher', 'A unilateral supine tricep extension using cable attachment.'),
('Triceps', 'Cables', 'Cable Tricep Kickback', 'A tricep extension moving arm from forward to backward extended position.'),
('Triceps', 'Dumbbells', 'Dumbbell Decline Skullcrusher', 'A tricep extension on decline bench for varied angle stimulus.'),
('Triceps', 'Dumbbells', 'Dumbbell Incline Skullover', 'A combination of pullover and tricep extension on incline bench.'),
('Triceps', 'Dumbbells', 'Dumbbell Overhead Tricep Extension', 'A bilateral tricep extension with dumbbell held overhead with both hands.'),
('Triceps', 'Dumbbells', 'Dumbbell Rolling Tricep Extension', 'A supine tricep extension with backward rolling motion of dumbbell.'),
('Triceps', 'Dumbbells', 'Dumbbell Seated Overhead Tricep Extension', 'A seated tricep extension with dumbbell overhead.'),
('Triceps', 'Dumbbells', 'Dumbbell Single Arm Overhead Tricep Extension', 'A unilateral tricep extension with arm overhead.'),
('Triceps', 'Dumbbells', 'Dumbbell Skullcrusher', 'A supine elbow extension exercise lowering dumbbells toward forehead.'),
('Triceps', 'Dumbbells', 'Dumbbell Tate Press', 'A supine tricep exercise lowering dumbbells with elbows flared toward chest.'),
('Triceps', 'Dumbbells', 'Dumbbell Tricep Kickback', 'A tricep extension moving arm from forward to fully extended position.'),
('Triceps', 'Machine', 'Machine Assisted Parralel Bar Dips', 'A vertical pressing exercise with partial weight supported by machine.'),
('Triceps', 'Machine', 'Machine Cable V Bar Push Downs', 'A tricep extension using V-shaped attachment on cable machine.'),
('Triceps', 'Smith Machine', 'Smith Machine Bodyweight Skullcrusher', 'A bodyweight tricep extension using fixed Smith machine bar.'),
('Triceps', 'Smith Machine', 'Smith Machine Close Grip Bench Press', 'A narrow-grip bench press using Smith machine for fixed bar path.'),
('Triceps', 'Smith Machine', 'Smith Machine Guillotine Bench Press', 'A bench press to neck area using Smith machine for fixed bar path.'),
('Triceps', 'Smith Machine', 'Smith Machine Skullcrusher', 'A supine tricep extension using Smith machine bar for stability.');


-- Step 6: Extract unique muscle groups and insert them
INSERT INTO muscle_groups (name)
SELECT DISTINCT muscle_group FROM temp_exercise_import
WHERE @can_proceed = 1
ORDER BY muscle_group;

-- Step 7: Extract unique equipment and insert them
INSERT INTO equipment (name)
SELECT DISTINCT equipment FROM temp_exercise_import
WHERE @can_proceed = 1
ORDER BY equipment;

-- Step 8: Insert exercises with proper references to muscle groups and equipment
INSERT INTO exercises (name, muscle_group_id, equipment_id, description)
SELECT 
    t.exercise_name,
    mg.id AS muscle_group_id,
    e.id AS equipment_id,
    t.description
FROM temp_exercise_import t
JOIN muscle_groups mg ON t.muscle_group = mg.name
JOIN equipment e ON t.equipment = e.name
WHERE @can_proceed = 1;

-- Step 9: Drop temporary table
DROP TEMPORARY TABLE IF EXISTS temp_exercise_import;

-- Commit the transaction
COMMIT;

-- Display confirmation message
SELECT IF(@can_proceed = 1, 'Exercise library has been reset and populated with data.', 'Reset operation was cancelled to protect data integrity.') AS 'Result';

-- Count the number of inserted records
SELECT 
    (SELECT COUNT(*) FROM muscle_groups) AS 'Muscle Groups',
    (SELECT COUNT(*) FROM equipment) AS 'Equipment',
    (SELECT COUNT(*) FROM exercises) AS 'Exercises';
